"""add_bsky_url_to_publish_attempts

Revision ID: 313cf88a0630
Revises: a1f4c8e92b3d
Create Date: 2026-06-19 15:49:13.489237
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '313cf88a0630'
down_revision = 'a1f4c8e92b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsky_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_attempts', schema=None) as batch_op:
        batch_op.drop_column('bsky_url')

    # ### end Alembic commands ###
