"""add submission_threads mapping

Revision ID: 3d15d8253969
Revises: 3f97cb40b05d
Create Date: 2026-06-18 17:40:07.865445
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3d15d8253969'
down_revision = '3f97cb40b05d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('source_discord_message_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'source_discord_message_id', name='uq_submission_thread_source')
    )
    with op.batch_alter_table('submission_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_threads_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_threads_source_discord_message_id'), ['source_discord_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_threads_source_discord_message_id'))
        batch_op.drop_index(batch_op.f('ix_submission_threads_board_id'))

    op.drop_table('submission_threads')
    # ### end Alembic commands ###
