"""add resolved metadata to submission_links

Revision ID: 3f97cb40b05d
Revises: b0e983047404
Create Date: 2026-06-18 16:42:56.363588
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3f97cb40b05d'
down_revision = 'b0e983047404'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_image_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_via', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_links', schema=None) as batch_op:
        batch_op.drop_column('resolved_via')
        batch_op.drop_column('resolved_image_path')
        batch_op.drop_column('resolved_image_url')
        batch_op.drop_column('resolved_description')
        batch_op.drop_column('resolved_title')

    # ### end Alembic commands ###
