"""add submission thread_id

Revision ID: 44eb6df703e8
Revises: e83986a05836
Create Date: 2026-06-17 21:54:59.756761
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '44eb6df703e8'
down_revision = 'e83986a05836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
