"""add image gate: submission embed fields + image_requests

Revision ID: b0e983047404
Revises: 44eb6df703e8
Create Date: 2026-06-18 16:29:45.623708
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b0e983047404'
down_revision = '44eb6df703e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_requests',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=False),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_requests_bot_message_id'), ['bot_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_image_requests_submission_id'), ['submission_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embed_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embed_thumb_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('embed_thumb_url')
        batch_op.drop_column('embed_description')
        batch_op.drop_column('embed_title')

    with op.batch_alter_table('image_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_requests_submission_id'))
        batch_op.drop_index(batch_op.f('ix_image_requests_bot_message_id'))

    op.drop_table('image_requests')
    # ### end Alembic commands ###
