"""initial m1 schema

Revision ID: e83986a05836
Revises: 
Create Date: 2026-06-17 18:39:22.947290
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e83986a05836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('discord_guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_discord_channel_id'), ['discord_channel_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_boards_discord_guild_id'), ['discord_guild_id'], unique=False)

    op.create_table('curators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curators_board_id'), ['board_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('source_discord_message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_display', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('graphic_status', sa.String(length=20), nullable=False),
    sa.Column('graphic_classification_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'source_discord_message_id', name='uq_submission_source_msg')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_source_discord_message_id'), ['source_discord_message_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('discord_attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('discord_url', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('spoiler', sa.Boolean(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('alt_text_status', sa.String(length=20), nullable=False),
    sa.Column('alt_text_body', sa.Text(), nullable=True),
    sa.Column('alt_text_author', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_discord_attachment_id'), ['discord_attachment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_submission_id'), ['submission_id'], unique=False)

    op.create_table('content_label_requests',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=False),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_label_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_label_requests_bot_message_id'), ['bot_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_label_requests_submission_id'), ['submission_id'], unique=False)

    op.create_table('source_requests',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=False),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_requests_bot_message_id'), ['bot_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_source_requests_submission_id'), ['submission_id'], unique=False)

    op.create_table('submission_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('raw_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('domain_family', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_links_submission_id'), ['submission_id'], unique=False)

    op.create_table('attachment_alt_text_requests',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=False),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment_alt_text_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_alt_text_requests_attachment_id'), ['attachment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_alt_text_requests_bot_message_id'), ['bot_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_attachment_alt_text_requests_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment_alt_text_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_alt_text_requests_submission_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_alt_text_requests_bot_message_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_alt_text_requests_attachment_id'))

    op.drop_table('attachment_alt_text_requests')
    with op.batch_alter_table('submission_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_links_submission_id'))

    op.drop_table('submission_links')
    with op.batch_alter_table('source_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_requests_submission_id'))
        batch_op.drop_index(batch_op.f('ix_source_requests_bot_message_id'))

    op.drop_table('source_requests')
    with op.batch_alter_table('content_label_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_label_requests_submission_id'))
        batch_op.drop_index(batch_op.f('ix_content_label_requests_bot_message_id'))

    op.drop_table('content_label_requests')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_submission_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_discord_attachment_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_source_discord_message_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_board_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('curators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curators_board_id'))

    op.drop_table('curators')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_discord_guild_id'))
        batch_op.drop_index(batch_op.f('ix_boards_discord_channel_id'))

    op.drop_table('boards')
    # ### end Alembic commands ###
